name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.puregero.serverutils.ServerUtilsPlugin
author: PureGero
api-version: 1.18
commands:
  setplayercount:
    description: Set the maximum player count
    permission: serverutils.setplayercount
  setviewdistance:
    description: Set the view distance
    permission: serverutils.setviewdistance
  setsimulationdistance:
    description: Set the simulation distance
    permission: serverutils.setsimulationdistance
  ping:
    description: Shows your ping
    permission: serverutils.ping
  subscribers:
    description: Displays the external servers subscribed to the chunk you're standing in
    permission: serverutils.subscribers
  instancesping:
    description: Check that all the instances are connected to eachother
    permission: serverutils.instancesping
  executeonallservers:
    description: Run a command on all servers
    permission: serverutils.executeonallservers
  setpersistence:
    description: Set the persistence required value for nearby mobs
    permission: serverutils.setpersistence
permissions:
  serverutils.setplayercount/:
    default: op
  serverutils.setviewdistance:
    default: op
  serverutils.setsimulationdistance:
    default: op
  serverutils.ping:
    default: true
  serverutils.subscribers:
    default: true
  serverutils.instancesping:
    default: true
  serverutils.executeonallservers:
    default: op
  serverutils.setpersistence:
    default: op